# docker-compose.yml

services:
  postgres-db:
    image: postgres:16  # Usa una versión estable reciente
    container_name: mi_postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Expone el puerto 5432 al host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos

volumes:
  postgres_data: # Define el volumen para que no pierdas datos al apagarlo